ory/polis

- README.md
- package.json
- src/controller/api.js
- src/controller/oauth.js
- src/env.js
- src/index.js
- src/jackson.js
- tweaked options passed to npm library
- expanded documentation for npm and the service
> Documentation for NPM library

- src/db/sql/entity/JacksonIndex.js
- src/db/sql/entity/JacksonStore.js
- src/db/sql/sql.js
- src/db/utils.js
- src/index.js
- wait until connection is established with SQL databases
- Fixed column types for supported SQL databases
> Wait for initial connection to sql databases

- src/saml/saml.js
Support parsing of SP metadata
> Support parsing of SP metadata

- README.md
- src/controller/oauth.js
- src/saml/claims.js
- src/saml/saml.js
Fix for mapping claims attributes to id, email, firstName, lastName where possible.
> map known claims attributes to id, email, firstName, lastName

- README.md
- package.json
- src/controller/api.js
- src/jackson.js
Adds a GET endpoint to the config API which returns the provider domain.
> added an api endpoint to get the saml configuration

- src/controller/api.js
- src/test/api.test.js
Handle the invalid request sends to the controller/api config() method
> Added field validation for the controller/api

- README.md
- src/jackson.js
- src/test/api.test.js
> IdP metadata fetch : Use GET instead of POST 

- README.md
- src/controller/api.js
- src/jackson.js
- src/test/api.test.js
> Feature delete idp conf

- npm/src/controller/oauth.ts
Process code_verifier first before checking for client_id and client_secret in the token route
> check for code_verifier first

- lib/utils.ts
- npm/src/controller/utils.ts
- pages/api/oauth/userinfo.ts
- pages/api/v1/saml/config.ts
API key validation was missing when we moved from express to next.js
> validate API key for config APIs

- npm/src/read-config.ts
> add webpackIgnore and update require ➡️ import

- .env.example
- .vscode/extensions.json
- lib/env.ts
- npm/src/controller/oauth.ts
- npm/src/index.ts
- npm/src/typings.ts
- npm/test/oauth.test.ts
Especially relevant when PKCE flow is not used
> added CLIENT_SECRET_VERIFIER for enhancing OAuth 2.0 security

- .env.example
Add `EXTERNAL_URL` to the .env.example
> Add EXTERNAL_URL to .env.example

- Dockerfile
- package-lock.json
- package.json
Updates node to 16.14.0
Update
> updated node to 16.14.0

- .github/workflows/main.yml
- npm/src/controller/oauth.ts
- npm/src/saml/saml.ts
- npm/src/typings.ts
> added x509data to AuthnRequest

- .github/workflows/main.yml
Workflow optimisations to speed up the cosign install process using HomeBrew.
> Cosign optimisations

- npm/src/controller/api.ts
- swagger/swagger.json
Fix the swagger spec by removing the example attributes
Paste the swagger.json file into https://editor.swagger.io/
> Fix the swagger.json

- components/saml/AddEdit.tsx
Update redirect url port 3000 to 3366 
> Update redirect url port 3000 to 3366 

- .vscode/extensions.json
- components/Layout.tsx
- components/saml/AddEdit.tsx
- package-lock.json
- package.json
- pages/_document.tsx
- pages/admin/saml/config/edit/[id].tsx
- pages/admin/saml/config/index.tsx
> Automatic class sorting with prettier plugin for tailwind

- lib/utils.ts
- pages/api/admin/saml/config/[[...slug]].ts
Removed API key validation from Admin API route.
> Fix api route auth

- npm/src/controller/oauth.ts
> Send requested tenant, product in the userinfo profile

- components/saml/AddEdit.tsx
- npm/src/controller/admin.ts
- npm/src/controller/api.ts
- npm/src/typings.ts
- npm/test/api.test.ts
- pages/admin/saml/config/edit/[id].tsx
- pages/api/admin/saml/config/[[...slug]].ts
- pages/api/v1/saml/config.ts
Response of getConfig is a little weird, flattening it.
> fixed tests

- npm/README.md
> Fix dead link

- lib/jackson.ts
- npm/src/controller/health-check.ts
- npm/src/index.ts
- npm/src/typings.ts
- pages/api/health.ts
Health Check for DB and Jackson Service and return the Status of service 
> Add readiness and health checks

- npm/src/db/mem.ts
- npm/src/db/mongo.ts
- npm/src/db/redis.ts
- npm/src/db/utils.ts
- npm/test/db.test.ts
- npm/tsconfig.json
- tsconfig.json
> Redis,Mem DB pagination, mongo init function changes and some unit test cover 

- npm/src/controller/api.ts
- npm/src/typings.ts
Support an array for redirectUrl. Currently we expect it to be a JSON encoded array which is backwards.
> support string | string [] for redirectUrl

- npm/src/controller/api.ts
- npm/src/controller/utils.ts
- npm/test/api.test.ts
This adds validation for POST/PATCH config endpoints
- Added validation to ensure redirectUrl list is limited to max 10
- Check urls are valid ones
Fixes #136 
Unit tests
> Validate urls in the config api request

- npm/src/controller/oauth.ts
- npm/test/oauth.test.ts
> Check client_secret if client_id is dummy

- README.md
Fix the link to the Jackson Doc
> Fix the link to the Doc

- npm/src/controller/oauth.ts
- npm/src/typings.ts
- npm/test/fixture.ts
- npm/test/oauth.test.ts
Adds support for encoded tenant product in `scope` param
> Read encoded tenant product from scope

- npm/package-lock.json
- npm/package.json
- npm/src/controller/oauth.ts
- npm/test/oauth.test.ts
- package-lock.json
> saml20 updates parseIssuer,validate and privatekey

- components/saml/AddEdit.tsx
Remove `Authorization` header from admin controller api call.
Unit tests
> Remove Authorization header

- lib/env.ts
- npm/src/controller/oauth.ts
- npm/src/controller/oidc-discovery.ts
- npm/src/typings.ts
> fixed default value for jwsAlg

- components/Layout.tsx
- components/saml/AddEdit.tsx
- e2e/admin.spec.ts
- npm/package-lock.json
- npm/package.json
- package-lock.json
- pages/admin/saml/config/index.tsx
> Text tweaks

- npm/package-lock.json
- npm/package.json
- package-lock.json
- package.json
Adds sharp package - https://nextjs.org/docs/messages/sharp-missing-in-production
> added sharp package for next.js to use in production

- npm/src/controller/oauth.ts
- npm/src/typings.ts
- npm/test/fixture.ts
- npm/test/oauth.test.ts
Adds validation for `redirect_uri` in code exchange step to token endpoint. After this clients won't be able to send arbitrary `redirect_uri` to obtain a token, it should match the one from the original authorization request.
> Validate redirect_uri in code exchange

- npm/src/controller/oauth.ts
- npm/test/fixture.ts
- npm/test/oauth.test.ts
Fixes an issue where the token exchange failed in IdP initiated SAML login.
> Fix IdP initiated saml login

- .github/workflows/uffizzi-env-delete.yaml
- .github/workflows/uffizzi-env-deploy.yaml
Tweaks Uffizzi workflows
CI/CD
> only run Uffizzi workflows for PRs

- npm/src/controller/oauth.ts
- npm/src/saml/x509.ts
The self Signed certificate had an issue with the expiry date, this PR has the fix for that where we are setting the expiry date to 2049-12-31T23:59:59Z.
echo <Public Key>  >> pub.pem && openssl x509 -enddate -noout -in pub.pem
> Self signed certificate expiry issue

- .github/workflows/main.yml
Fixes brew install issue in GA
> use cosign-installer instead of brew

- components/saml/AddEdit.tsx
Shows the IdP cert expiry on Admin UI saml config view page
Fixes #118 
Admin UI should show the Certificate expiry
> Showing IdP cert expiry and warning on UI

- .github/workflows/uffizzi-env-delete.yaml
> cleanup Uffizzi containers when PR is closed

- .github/workflows/uffizzi-env-delete.yaml
> attempting to fix the delete workflow

- npm/package-lock.json
- npm/package.json
- package-lock.json
> Pin `axios`

- npm/src/loadConnection.ts
- uffizzi/saml_config/boxyhq.js
Fixes pre load config loading in Windows.
> fixed file paths for Windows

- npm/package-lock.json
- npm/src/controller/oauth.ts
- package-lock.json
- pages/idp/select.tsx
Modified the label to display as either `name (provider)` or `provider`.
> Fix IdP-Select screen connection label

- npm/src/controller/oauth.ts
- npm/src/saml/claims.ts
- npm/src/typings.ts
- swagger/swagger.json
Adds roles and groups to the profile.
> Roles and groups

- .env.example
- components/Sidebar.tsx
- components/layouts/AccountLayout.tsx
- pages/admin/auth/login.tsx
Replace text **Admin UI** with **Admin Portal**
> Replace the text Admin UI with Admin Portal

- .github/workflows/main.yml
This would allow safe access to configured secrets in the action run for PR from forks.
> Update triggering event

- .github/workflows/build_pr-docker-image.yaml
- .github/workflows/uffizzi-env-deploy.yaml
- Updated Uffizzi action to `v2.6.1`
- replace `::set-output` with env vars
Test Pull Request
https://github.com/waveywaves/boxyhq-jackson/pull/5
> update uffizzi version + remove deprecated setoutput

- components/connection/AddEdit.tsx
- npm/src/controller/api.ts
- npm/src/controller/connection/saml.ts
- npm/src/controller/utils.ts
- npm/src/typings.ts
- npm/test/sso/saml_idp_api.test.ts
Fixes #94 
https://www.loom.com/share/35bd610ec3aa43459be43ac6e9e41df5
> Read xml metadata from a url when setting the config

- npm/package-lock.json
- npm/package.json
- package-lock.json
> updated saml20 (and xmldom)

- npm/package-lock.json
- npm/src/controller/oauth.ts
- package-lock.json
Idea is to use it as a makeshift email for auth systems that cannot work without an email
> send ripemd160 hash of the id as idHash

- npm/src/controller/sp-config.ts
- npm/src/typings.ts
- pages/api/well-known/sp-metadata.ts
> moved sp-metadata logic to npm

- next.config.js
- npm/tsconfig.json
- tsconfig.json
> enable sourcemaps

- .github/workflows/codesee-arch-diagram.yml
- .github/workflows/main.yml
- Dockerfile
- package-lock.json
- uffizzi/Dockerfile
> Upgraded to node 18.12.1

- npm/package-lock.json
- npm/package.json
- package-lock.json
> updated saml20

- .github/workflows/main.yml
- Dockerfile
Enables multi platform build for docker image
> Enable multi platform build for docker image

- components/connection/ConnectionList.tsx
- components/connection/Edit.tsx
- components/connection/fieldCatalog.ts
- components/connection/utils.tsx
- npm/src/controller/connection/oidc.ts
- npm/src/controller/connection/saml.ts
> Fixed edit view for sso connections

- ee/federated-saml/api/admin/[id]/index.ts
- ee/federated-saml/api/admin/index.ts
- ee/federated-saml/api/sso.ts
- lib/strings.ts
> tweaks to ee text

- pages/admin/auth/login.tsx
Fixes state handling in the custom sign in page. (Used to briefly display the login page on signing in via magic link.)
> Fix state handling for custom sign in page

- .github/workflows/main.yml
> trying to fix build

- components/Navbar.tsx
- components/connection/WellKnownURLs.tsx
- ee/federated-saml/pages/index.tsx
Fixes link styling and adds missing aria* attributes for icon
> Fix styling for links

- npm/src/directory-sync/Base.ts
Switches uuid with crypto.randomUUID
> Switched uuid with crypto.randomUUID

- next.config.js
- package-lock.json
- package.json
(next.js has fixed the issue in middleware which prevented payloads > 16kb)
> cleaned up experimental flag and node-fetch

- npm/package-lock.json
- npm/package.json
- package-lock.json
> updated deps including axios

- components/retraced/ProjectDetails.tsx
- package-lock.json
- package.json
- pages/admin/retraced/projects/[id]/events.tsx
> Updated react-daisyui

- components/connection/EditConnection.tsx
- pages/api/admin/retraced/projects/index.ts
Fixed the API endpoint for delete sso connection from the setup link page
> Setup link bug fix

- tsconfig.json
Fixes duplicate key in tsconfig
> Fix duplicate key in tsconfig.json

- lib/ui/hooks/usePaginate.ts
Append the `offset` to the query string of the page URL when paginating.
> append the `offset` to the query string of the page URL when paginating

- lib/ui/retraced.ts
- locales/en/common.json
- pages/admin/retraced/projects/index.tsx
- pages/api/admin/retraced/projects/index.ts
Pagination support for Audit logs projects
> Pagination related changes for audit logs projects

- Dockerfile
- package-lock.json
- package.json
> Copy sdk/ui/react in case we have deps in the future

- components/connection/CreateConnection.tsx
- npm/src/controller/oauth.ts
- npm/src/typings.ts
- npm/test/sso/fixture.ts
- npm/test/sso/saml_idp_oauth.test.ts
> Forceauth fix

- .github/workflows/main.yml
> GitHub actions fixes

- package-lock.json
- pages/api/auth/[...nextauth].ts
Replaces HTTP fetch calls with controller methods.
> Use OAuthController methods with idp login

- .github/workflows/main.yml
Updated GitHub Actions to use Syft for docker image SBOMs creation
> Switching to Syft for docker image SBOMs

- npm/package-lock.json
- package-lock.json
- package.json
> Update react types and lock files

- lib/jackson.ts
- package-lock.json
Fixes the key in the global object
> Fix jackson init

- locales/en/common.json
- npm/src/controller/saml-handler.ts
- pages/error.tsx
Tweaked the text to be generic while displaying error page and also inside `resolveConnection`.
> Generalise error display

- npm/src/controller/connection/saml.ts
> switched promise catch to try/catch

- package-lock.json
- package.json
- sdk/ui/react/package-lock.json
- sdk/ui/react/package.json
> Windows run scripts fix

- sdk/ui/react/src/Login/README.md
Changes the casing of the styles property so that It matches with the default styled-jsx used in React.
> Change casings for the styles property to match styled-jsx

- npm/package-lock.json
- npm/src/db/mongo.ts
- npm/src/index.ts
- package-lock.json
Fixes Jackson's init that resulted in leaking db connections.
> Fix db connection leak

- components/dsync/CreateDirectory.tsx
- ee/branding/api/admin/index.ts
- ee/federated-saml/api/admin/[id]/index.ts
- ee/federated-saml/api/admin/index.ts
- ee/federated-saml/api/sso.ts
- ee/federated-saml/pages/index.tsx
- npm/src/ee/branding/index.ts
- npm/src/ee/common/checkLicense.ts
- npm/src/ee/federated-saml/app.ts
- npm/src/ee/federated-saml/index.ts
- npm/src/ee/federated-saml/sso.ts
- npm/src/index.ts
- Removed the license check from the `/api/admin/*` routes. Now the license check is handled by the `/npm` controller methods and throws a 403 if the license is not valid.
- Added a new method `throwIfInvalidLicense` that throws a 403 if the license is not valid.
> Correct License Verification for EE Feature Controllers 

- npm/package-lock.json
- npm/package.json
- package-lock.json
Downgrade pg dependency to 8.10.0. 
Upgrading pg to 8.11.0 results in below error:
`error connecting to engine: sql, type: postgres db: DriverPackageNotInstalledError: Postgres package has not been found installed. Try to install it: npm install pg --save`
More info: https://github.com/typeorm/typeorm/issues/10076
> Fix for `DriverPackageNotInstalledError` related to pg upgrade

- README.md
> Updated README.md to add OpenSSF badge

- Dockerfile
- uffizzi/Dockerfile
> updated to 18.16.1-alpine3.18

- npm/package-lock.json
- npm/package.json
- package-lock.json
> npm lock files cleanup and added missing peer deps

- ee/branding/api/index.ts
- ee/federated-saml/api/metadata.ts
- ee/federated-saml/api/sso.ts
- pages/api/admin/connections/[clientId].ts
- pages/api/admin/retraced/projects/[id]/groups.ts
- pages/api/admin/retraced/projects/[id]/index.ts
- pages/api/admin/retraced/projects/[id]/viewer-token.ts
- pages/api/admin/retraced/projects/index.ts
- pages/api/admin/terminus/models/[id]/index.ts
- pages/api/oauth/saml.ts
- pages/api/scim/oauth/authorize.ts
- pages/api/v1/connections/exists.ts
- pages/api/v1/connections/index.ts
> added missing awaits

- npm/src/controller/api.ts
- swagger/swagger.json
> Update Open API spec for SSO

- pages/api/admin/terminus/models/[id]/index.ts
> send api-key (custom header will be removed later)

- e2e/ui/settings/sso.spec.ts
Temporarily disable e2e for OIDC SSO until https://github.com/boxyhq/jackson/pull/1405 is ready
> Disable OIDC e2e tests

- Dockerfile
- npm/package-lock.json
- package-lock.json
- package.json
- postbuild.ts
- prebuild.ts
1. Prepend cross-env to the start script. This will make it work in windows environment.
2. Switch pre/post-build folder copying steps to cross-platform scripts.
> Fix build setup for windows

- README.md
> Added docs link at the top / video of connection in the center

- components/terminus/blocks/customblocks.ts
Adds options of FPE (FF1 & FF3_1) algorithms to CUE terminus model
Create terminus model with FPE encryption
> Added Support of FPE FF1 & FF3_1

- Dockerfile
- uffizzi/Dockerfile
> updated node

- npm/src/directory-sync/scim/DirectoryConfig.ts
- npm/src/opentelemetry/metrics.ts
This PR add open telemetry metrics for directory sync connections.
> Add metrics for directory sync

- Dockerfile
- uffizzi/Dockerfile
> Updated nodejs to 18.18.0

- README.md
> Add Hacktoberfest badge to the README.md

- kustomize/overlays/demo/kustomization.yaml
- kustomize/overlays/demo/services/kustomization.yaml
> fixed demo services

- ee/federated-saml/api/sso.ts
- pages/api/oauth/authorize.ts
- pages/api/oauth/oidc.ts
- pages/api/oauth/saml.ts
- pages/api/scim/oauth/authorize.ts
> Fixed redirect requests

- kustomize/overlays/demo/kustomization.yaml
- kustomize/overlays/demo/mocksaml-deployment.yaml
- kustomize/overlays/demo/services/kustomization.yaml
- kustomize/overlays/demo/services/mocksaml-service.yaml
> mocksaml deployment

- components/setup-link-instructions/CreateSSOConnection.tsx
- pages/_app.tsx
Loads the SDK stylesheet and updates the style setting for Create connection components inside setup link pages.
> Fix sdk css load

- Dockerfile
> updated node to 18.18.2

- kustomize/overlays/demo/services/jackson-service.yaml
- kustomize/overlays/demo/services/mocksaml-service.yaml
- kustomize/overlays/prod-eu/services/jackson-service.yaml
- kustomize/overlays/prod-eu/services/mocksaml-service.yaml
- package.json
> turn off http, update ssl security policy

- kustomize/base/services/internal/jackson-internal-service.yaml
- kustomize/base/services/internal/kustomization.yaml
- kustomize/base/services/kustomization.yaml
- kustomize/overlays/demo/services/kustomization.yaml
- kustomize/overlays/demo/services/mocksaml-service.yaml
- kustomize/overlays/prod-eu/services/kustomization.yaml
- kustomize/overlays/prod-eu/services/mocksaml-service.yaml
- package.json
> updated mocksaml services

- kustomize/base/migration/kustomization.yaml
- kustomize/base/migration/migratepg-job.yaml
- kustomize/overlays/demo/kustomization.yaml
- kustomize/overlays/demo/migratepg-job.yaml
- kustomize/overlays/postgres/kustomization.yaml
- kustomize/overlays/prod-eu/kustomization.yaml
- kustomize/overlays/prod-eu/migratepg-job.yaml
> fixed migratepg job

- kustomize/base/migration/migratepg-job.yaml
> set ttlSecondsAfterFinished: 0 so cleanup happens after job is complete

- .github/workflows/main.yml
- e2e/ui/settings/sso.spec.ts
- kustomize/overlays/prod-eu/kustomization.yaml
> updated mocksaml placeholder

- e2e/api/v1/directory-sync/directories.spec.ts
- npm/src/directory-sync/scim/DirectoryConfig.ts
- pages/api/v1/dsync/[directoryId].ts
- pages/api/v1/dsync/index.ts
Fix directory sync `/api/v1/dsync` PATCH API
> Fix directory sync /api/v1/dsync PATCH API

- .github/workflows/main.yml
- Dockerfile
> updated to node 20 since node 18 is now in maintenance mode

- next.config.js
> added sts, xframe and xcontenttype headers

- npm/src/controller/connection/oidc.ts
- npm/src/controller/utils.ts
- npm/src/typings.ts
> Attach friendlyProviderName to OIDC

- middleware.ts
- pages/api/v1/dsync/cron/process-events.ts
- pages/api/v1/dsync/cron/sync-google.ts
Replace apiKey query params with Authorization header for cron endpoints
> Replace apiKey query params with Authorization header for cron endpoints

- Dockerfile
- package-lock.json
- package.json
> updated node to v20.10.0

- package-lock.json
- package.json
This reverts commit 7fd4b73104ae00e43c7f805b2f7e63953d256189.
> Revert "Bump sharp from 0.32.6 to 0.33.0 (#1994)"

- components/connection/WellKnownURLs.tsx
> Add cards to categorize well known URLS

- npm/package-lock.json
- npm/src/controller/setup-link.ts
- npm/src/index.ts
Use `externalUrl` instead of `NEXTAUTH_URL` for creating the setup link.
> Fix setup link url creation

- e2e/api/scim/v2.0/groups.spec.ts
- npm/package-lock.json
- npm/src/directory-sync/scim/DirectoryGroups.ts
- npm/src/directory-sync/scim/DirectoryUsers.ts
- npm/test/dsync/data/users.ts
- npm/test/dsync/groups.test.ts
- npm/test/dsync/users.test.ts
- npm/test/dsync/webhooks.test.ts
- package-lock.json
[Test result](https://www.runscope.com/radar/wg4sw9jbhkty/f804f9d9-5707-4c19-adf3-c43b5dd7cf50/history/8e88d21b-7ae7-4735-93e3-cb89e9131a3b)
> Pass the okta runscope tests for SCIM

- ee/federated-saml/pages/edit.tsx
- npm/src/ee/federated-saml/app.ts
- swagger/swagger.json
- Prevent updating the `entityId` of an existing SAML federation app.
- Prevent creating multiple apps for same tenant and product.
> Prevent updating the `entityId` of the SAML federation app.

- npm/package-lock.json
- package-lock.json
- package.json
> updated axios to v1.6.5

- npm/package-lock.json
- npm/src/controller/oauth.ts
- npm/src/typings.ts
- npm/test/sso/fixture.ts
- npm/test/sso/oidc_idp_oauth.test.ts
- package-lock.json
- pages/api/oauth/oidc.ts
Fixes https://github.com/boxyhq/jackson/issues/2074
RFC: https://datatracker.ietf.org/doc/html/rfc9207
> Rfc9207 support for OIDC connections

- npm/package-lock.json
- npm/src/controller/oauth.ts
- npm/src/typings.ts
- package-lock.json
Brings back the old type name for compatibility with existing setups.
> Fix type for backward compatibility

- npm/test/db/db.test.ts
> randomize sessionStore to avoid tests failing in concurrent builds

- pages/api/v1/stats/index.ts
Adds stats to get sso and dsync connections counts
> Admin stats

- .github/workflows/main.yml
- _dev/docker-compose.yml
- kustomize/overlays/dbs/mongo/mongo.yaml
> updated mongo

- ee/federated-saml/pages/edit.tsx
- ee/federated-saml/pages/new.tsx
- kustomize/overlays/demo/kustomization.yaml
- kustomize/overlays/prod-eu/kustomization.yaml
- locales/en/common.json
> added onBlur to TagsInput

- ee/federated-saml/pages/new.tsx
- pages/admin/federated-saml/new.tsx
Read entityId prefix value from env
> Read entityId prefix value from env

- next.config.js
> Enable server sourcemaps

- npm/package-lock.json
- npm/package.json
- npm/src/ee/federated-saml/sso.ts
- npm/src/saml/lib.ts
- package-lock.json
> SAML Fed request processing fixes

- npm/package-lock.json
- npm/package.json
- npm/src/controller/logout.ts
- package-lock.json
> move logout parsing to saml20

- ee/federated-saml/api/sso.ts
- npm/src/controller/sso-handler.ts
Proper error handling for SAML Federated route
> Proper error handling for SAML Federated route

- npm/src/controller/oauth/allowed.ts
Don't allow redirect to URL placeholder `http://_boxyhq_redirect_not_in_use`
> Don't allow redirect to URL placeholder

- npm/src/controller/sso-handler.ts
- npm/src/ee/federated-saml/types.ts
> added AttributeMapping type

- pages/api/admin/setup-links/index.ts
> fixed setup links pagination

- components/EmptyState.tsx
- components/connection/ConnectionList.tsx
- components/dsync/DirectoryList.tsx
- components/setup-link/SetupLinkList.tsx
- ee/federated-saml/pages/edit.tsx
- ee/federated-saml/pages/index.tsx
- locales/en/common.json
- pages/admin/directory-sync/[directoryId]/events/index.tsx
- pages/admin/retraced/projects/index.tsx
- pages/admin/sso-tracer/index.tsx
> tweaks to align with SaaS app

- npm/package-lock.json
- npm/package.json
- package-lock.json
> updated package-lock

- components/connection/ConnectionList.tsx
- components/setup-link-instructions/CreateSSOConnection.tsx
- locales/en/common.json
> Setup link fixes

- pages/admin/settings/sso-connection/new.tsx
Fixes https://github.com/boxyhq/jackson/issues/2317
> Fix for adminPortalSSODefaults to be read correctly at build time

- Dockerfile
> node 20.11.1

- .github/workflows/main.yml
- components/terminus/Blockly/BlocklyComponent.tsx
- lib/ui/hooks/useKeyPress.ts
- npm/package.json
- npm/test/db/db.test.ts
- pages/admin/retraced/index.tsx
> run planetscale test on local mysql db

- internal-ui/src/setup-link/SetupLinkInfoModal.tsx
- internal-ui/src/setup-link/SetupLinks.tsx
> Fix setup link badge

- Dockerfile
- internal-ui/package-lock.json
- internal-ui/package.json
- package-lock.json
- package.json
> updated nextjs

- package-lock.json
- package.json
> removed swagger-cli

- npm/package-lock.json
- package-lock.json
- package.json
- playwright.config.ts
> run playwright against Chrome instead of Chromium

- lib/env.ts
- npm/src/directory-sync/batch-events/queue.ts
- npm/src/directory-sync/utils.ts
- npm/src/event/index.ts
- npm/src/event/webhook.ts
- npm/src/typings.ts
> print dsync webhooks to console

- pages/api/setup/[token]/directory-sync/[directoryId]/index.ts
The `google_authorization_url` is missing in the API response. This PR fixes it.
> [Dsync setup link api response] Add google_authorization_url in response

- pages/api/v1/stats/index.ts
- pages/api/v1/stats/product.ts
Added new route to get the sso & dsync connection counts using product ids & type
> New API for getStats

- internal-ui/src/federated-saml/Edit.tsx
- internal-ui/src/federated-saml/NewFederatedSAMLApp.tsx
- locales/en/common.json
- npm/src/controller/oauth.ts
- pages/api/oauth/token.ts
> Verify client id and secret in OIDC Federation pkce flow

- internal-ui/package-lock.json
- npm/package-lock.json
- npm/package.json
- package-lock.json
Reverts mysql2 which seems to be causing a `RangeError: Maximum call stack size exceeded` in nextjs build.
> revert mysql2 update

- internal-ui/src/federated-saml/FederatedSAMLApps.tsx
> default type for fedapp is saml

- kustomize/overlays/demo/kustomization.yaml
- kustomize/overlays/prod-eu/kustomization.yaml
- skaffold-demo-mocksaml-services.yaml
- skaffold-demo-mocksaml.yaml
- skaffold-demo-services.yaml
- skaffold-demo.yaml
- skaffold-dynamodb.yaml
- skaffold-mariadb.yaml
- skaffold-mongo.yaml
- skaffold-mssql.yaml
- skaffold-mysql.yaml
- skaffold-postgres.yaml
- skaffold-prod-eu-mocksaml-services.yaml
- skaffold-prod-eu-mocksaml.yaml
- skaffold-prod-eu-services.yaml
- skaffold-prod-eu.yaml
> updated skaffold

- .github/workflows/main.yml
Set github actions artifact retention to 1 day
> chore: Update artifact upload retention to 1

- npm/src/directory-sync/non-scim/google/api.ts
- npm/test/dsync/google_api.test.ts
> use customer query param instead of domain to fetch all users

- ee/product/api/[productId].ts
- npm/src/ee/product/index.ts
> chore: Delete product config api

- pages/api/v1/dsync/events/index.ts
- pages/api/v1/dsync/groups/index.ts
- pages/api/v1/dsync/users/index.ts
> fixed wrong response in dsync events

- internal-ui/package-lock.json
- npm/package-lock.json
- package-lock.json
- package.json
> updated react

- pages/api/v1/stats/index.ts
- pages/api/v1/stats/product.ts
> Stats for Identity Federation Apps

- lib/development-mode.ts
> fixes wrong EE check

- npm/src/controller/oauth.ts
Fixes a bug where an error in SAML IdP initiated flow causes the trace to not be recorded.
> Fix property access in saml response path.

- .prettierrc.js
- npm/src/index.ts
- npm/src/typings.ts
- pages/api/oauth/saml.ts
> cleanup of preLoadedConfig

- npm/src/db/redis.ts
- Redis createClient fix: URL is not a valid socketOption.
- [x ] Bug fix (non-breaking change which fixes an issue)
> fix: redis url does not come under socketOptions

- internal-ui/src/setup-link/SetupLinkInfo.tsx
- internal-ui/src/shared/InputWithCopyButton.tsx
> Added scroll to top for created setups links

- e2e/ui/Enterprise SSO/setup_link.spec.ts
> Added tests for testing mdx generated source of setup link steps

- npm/src/db/sql/sql.ts
> fix: turso stream inactive

- .github/workflows/main.yml
Download artifact action was giving error when downloading sbom files.
> SBOM artifact issue fixes

- pages/api/well-known/openid-configuration.ts
> enable cors for the oidc well known config url

- npm/src/controller/oauth.ts
Fixes an issue where the recorded trace won't have the tenant/product in the context. This will result in missed traces when fetching traces by product.
> Record OIDC fed tenant/product in requested

- components/terminus/Blockly/BlocklyComponent.tsx
- components/terminus/blocks/customblocks.ts
- components/terminus/blocks/generator.ts
> fixed publish of model

- components/terminus/blocks/customblocks.ts
- components/terminus/blocks/generator.ts
> streamlined model generation, more extensible now

- .github/workflows/main.yml
- _dev/docker-compose.yml
- kustomize/overlays/dbs/dynamodb/dynamodb.yaml
- kustomize/overlays/dbs/mariadb/mariadb.yaml
- kustomize/overlays/dbs/mongo/mongo.yaml
- kustomize/overlays/dbs/mssql/mssql.yaml
- kustomize/overlays/dbs/mysql/mysql.yaml
- kustomize/overlays/dbs/postgres/postgres.yaml
- kustomize/overlays/demo/kustomization.yaml
- kustomize/overlays/demo/mocksaml/kustomization.yaml
- kustomize/overlays/dynamodb/kustomization.yaml
- kustomize/overlays/mariadb/kustomization.yaml
- kustomize/overlays/mongo/kustomization.yaml
- kustomize/overlays/mssql/kustomization.yaml
- kustomize/overlays/mysql/kustomization.yaml
- kustomize/overlays/postgres/kustomization.yaml
- kustomize/overlays/prod-eu/kustomization.yaml
- kustomize/overlays/prod-eu/mocksaml/kustomization.yaml
> updated dbs

- .env.example
- .github/workflows/main.yml
- npm/src/db/db.ts
- npm/test/db/db.test.ts
> support a 32 byte key

- npm/src/db/encrypter.ts
> aes gcm uses 12 bytes iv

- e2e/api/v1/directory-sync/directories.spec.ts
- e2e/api/v1/directory-sync/events.spec.ts
- e2e/support/fixtures/dsync-page.ts
- e2e/support/fixtures/setuplink-ds-page.ts
- e2e/ui/Directory Sync/connections.spec.ts
- e2e/ui/Directory Sync/setup_link_ds.spec.ts
- next-env.d.ts
- npm/package-lock.json
- package-lock.json
- package.json
> updated playwright

- components/Sidebar.tsx
- components/layouts/AccountLayout.tsx
- locales/en/common.json
- pages/admin/auth/login.tsx
> Fetch branding and replace placeholder

- internal-ui/package-lock.json
- internal-ui/package.json
- npm/package-lock.json
- package-lock.json
- package.json
> updated cookie, vite

- npm/src/db/mem.ts
- npm/src/db/redis.ts
- npm/src/db/utils.ts
- npm/test/db/db.test.ts
> fix for redis getAll() on ttl stores

- kustomize/overlays/demo/kustomization.yaml
- lib/jackson.ts
- npm/src/db/db.ts
> fixed init of jackson lib

- Dockerfile
- pages/api/openid-client.ts
> dummy import of openid-client to get nextjs to leave it in node_modules

- lib/jackson.ts
> small tweak to return type

- npm/package.json
- npm/src/controller/oauth.ts
- npm/test/sso/fixture.ts
- npm/test/sso/saml_idp_oauth.test.ts
generate a per code/token encryption key and send it to the client, store the encrypted value so that PII exposure of storing profile is dropped to zero
> Store encrypted profile information with no way to access it without the key which is sent to client and never stored on the server

- Dockerfile
- internal-ui/package-lock.json
- npm/package-lock.json
- package-lock.json
- package.json
> set override for mongodb

- .env.example
- lib/env.ts
- npm/src/controller/api.ts
- npm/src/controller/connection/oidc.ts
- npm/src/controller/connection/saml.ts
- npm/src/ee/ory/ory.ts
- npm/src/index.ts
- npm/src/typings.ts
> Revert "cleanup"

- components/dsync/EditDirectory.tsx
- internal-ui/src/dsync/DirectoryInfo.tsx
- internal-ui/src/types.ts
- locales/en/common.json
- npm/src/directory-sync/non-scim/google/api.ts
- npm/src/directory-sync/scim/DirectoryConfig.ts
- npm/src/directory-sync/types.ts
- npm/test/dsync/directories.test.ts
- npm/test/dsync/google_api.test.ts
- npm/test/dsync/google_oauth.test.ts
- pages/api/admin/directory-sync/index.ts
- pages/api/setup/[token]/directory-sync/[directoryId]/index.ts
- pages/api/setup/[token]/directory-sync/index.ts
- swagger/swagger.json
> cleanup unused google_domain

- npm/src/directory-sync/scim/DirectoryGroups.ts
- npm/src/directory-sync/scim/DirectoryUsers.ts
- pages/api/auth/[...nextauth].ts
> protect against timing attacks during login checks

- npm/src/controller/oauth.ts
> Add `login_hint` to session.requested

- npm/src/controller/oauth.ts
- npm/src/ee/identity-federation/idp-login.ts
- npm/src/ee/identity-federation/sso.ts
- npm/src/opentelemetry/metrics.ts
> Capture OTEL metrics in Identity Federation

- lib/utils.ts
> url encode error json sent in cookie

- .github/workflows/main.yml
- package.json
> stop after first fail

- pages/setup/[token]/sso-connection/new.tsx
> Validate idp, step params to prevent unwanted file access

- npm/package.json
> set timeout for tap tests

- npm/src/controller/api.ts
- swagger/swagger.json
> Acs url override jsdoc changes

- npm/src/db/db.ts
- npm/src/db/dynamoDb.ts
- npm/src/db/mem.ts
- npm/src/db/mongo.ts
- npm/src/db/redis.ts
- npm/src/db/sql/sql.ts
- npm/src/db/utils.ts
- npm/src/opentelemetry/metrics.ts
- npm/src/typings.ts
- npm/test/db/db.test.ts
> DB pooling configuration support and otel metrics

- e2e/api/v1/sso/jwks.spec.ts
- npm/src/controller/oauth.ts
- npm/src/controller/utils.ts
- npm/test/sso/saml_idp_oauth.test.ts
- tsconfig.json
> Fix for esm module issue for jose

- internal-ui/package-lock.json
- package-lock.json
- package.json
- pages/idp/select.tsx
- Added styled components
- Created a global style using styled components which sets style based on primaryColor
> Changes for resolving react-hydration issue:

- npm/src/controller/api.ts
- npm/src/controller/connection/saml.ts
- npm/src/controller/oauth.ts
- npm/src/controller/sso-handler.ts
- npm/src/typings.ts
- swagger/swagger.json
> added samlAudienceOverride

- npm/src/controller/connection/saml.ts
- npm/src/controller/oauth.ts
- npm/src/controller/utils.ts
> SSO URL validation

- .env.example
- lib/env.ts
- npm/src/controller/oauth.ts
- npm/src/typings.ts
> added an option to flatten raw claims

- internal-ui/package-lock.json
- npm/package-lock.json
- npm/package.json
- npm/src/controller/connection/saml.ts
- npm/test/sso/saml_idp_api.test.ts
- package-lock.json
> disallow private IPs in metadata urls

- .env.example
- npm/src/controller/oauth.ts
- npm/test/sso/saml_idp_oauth.test.ts
- npm/test/sso/saml_idp_oauth_flattened.test.ts
> send full profile in id_token

- .env.example
- components/Sidebar.tsx
- components/layouts/AccountLayout.tsx
- ee/branding/api/index.ts
- lib/env.ts
> added options to hide audit logs and idfed

- npm/src/ee/identity-federation/app.ts
- swagger/swagger.json
> Updated swagger schemas

- npm/src/db/db.ts
> Clear setInterval on db close in npm package

- npm/src/db/sql/sql.ts
> clear timer on db close

- npm/src/db/db.ts
* Clear setInterval on db close in npm package
* Flush db stats before closing db instead of after.
---------
> Clear setInterval on db close in npm package (#3876)

- npm/src/controller/oauth.ts
> pkce flow requires a code_verifier for token exchange

- pages/api/logout/callback.ts
> Support GET method for SLO callback

- npm/src/controller/oauth/oidc-client.ts
- npm/src/controller/utils.ts
> rewrite request to tunnel local Ory address to k8s svc

- .env.example
- CONTRIBUTING.md
- README.md
- internal-ui/package.json
- package.json
> fixed link

- CODE_OF_CONDUCT.md
- app.json
- components/PoweredBy.tsx
- components/setup-link-instructions/generic-oidc/1.mdx
- components/setup-link-instructions/generic-saml/1.mdx
- components/setup-link-instructions/generic-saml/2.mdx
- components/setup-link-instructions/rippling/2.mdx
- locales/en/common.json
- npm/README.md
- npm/package.json
- npm/src/controller/sp-config.ts
- npm/src/directory-sync/scim/WebhookEventsLogger.ts
- npm/src/ee/identity-federation/index.ts
- npm/src/saml/x509.ts
- pages/admin/auth/login.tsx
- pages/well-known/oidc-configuration.tsx
- pages/well-known/saml-configuration.tsx
- performance-test/k6/idFed-load-test.js
- swagger/swagger-definition.js
- swagger/swagger.json
> chore: renamed references to boxyhq

- components/setup-link-instructions/generic-saml/2.mdx
- e2e/ui/Enterprise SSO/setup_link.spec.ts
> chore: update wording in generic-saml

- internal-ui/package-lock.json
- npm/package-lock.json
- package-lock.json
> sync package-lock files
