src/controller/oauth.js
src/index.js

Google SAML doesn't send an id, we use the email hash to fill it up instead

Add id to profile.claims if it is missing

---

README.md
app.json

Fixes #56. Include `EXTERNAL_URL` for setting the jackson service endpoint which is then used to construct the SAML request internally. 
User will need to set below vars while deploying
For Vercel: The URL is usually https://`repo-name`.vercel.app
For Heroku: https://`app-name`.herokuapp.com

Add EXTERNAL_URL to be set in env

---

npm/src/controller/oauth.ts
package-lock.json
package.json

Fixes the issue where SAML metadata has the same entity ID but for different applications.

Fixed multiple configs match (same entityID)

---

pages/api/v1/saml/config/exists.ts

Added a `config/exists` API to return if a config exists, same as get config but without any data being returned.

Config exists API endpoint

---

npm/src/controller/oauth.ts

When client_id is used the requested params don't include tenant and product. This PR adds it.

Set requested tenant and product when using client_id

---

npm/src/controller/oauth.ts
npm/src/typings.ts
npm/test/fixture.ts
npm/test/oauth.test.ts

Adds support for custom OAuth param `resource` and extracts tenant and product from there if present.

Support encoded tenant and product in the resource OAuth param

---

components/saml/AddEdit.tsx

UI Fixes for Checkbox on Edit SAML Connection page.
Hiding the IdP expiry field & label in case it is not present.

UI fixes for ForceAuthn

---

.github/workflows/build_pr-docker-image.yaml
.github/workflows/uffizzi-env-deploy.yaml

This update adds support for previews from forked repos. So any contributor should be able to see previews created from their forks of jackson.
ghcr.io is replaced with ttl.sh also in this case. The images won't be pushed to ghcr further polluting space with preview images. Instead images would be pushed to ttl.sh.

Update uffizzi workflow to latest version

---

pages/api/well-known/sp-metadata.ts

Fixes sp metadata by using prefixes, some providers fail parsing it as valid xml.

added prefix to sp metadata

---

npm/src/controller/oauth.ts
npm/test/sso/fixture.ts
npm/test/sso/saml_idp_oauth.test.ts

In case of IdP initiated SAML flow, codeVal will contain a `isIdPFlow` flag set to true.Later in token endpoint this will be used to skip the requested tenant product check.

Fix for token exchange failure in IdP initiated SAML login

---

npm/src/controller/connection/oidc.ts
npm/src/controller/connection/saml.ts
npm/src/controller/utils.ts
npm/src/directory-sync/DirectoryConfig.ts

This PR validate the tenant and product to prevent the namespace collision. Disallowed the character (`:`) that are not allowed in the tenant and product name.

Validate the tenant and product to prevent the namespace collision

---

ee/federated-saml/api/admin/[id]/index.ts
ee/federated-saml/api/admin/index.ts
ee/federated-saml/api/metadata.ts
ee/federated-saml/api/sso.ts
package-lock.json
pages/api/admin/connections/[clientId].ts
pages/api/admin/connections/idp-entityid.ts
pages/api/admin/connections/index.ts
pages/api/admin/directory-sync/[directoryId]/events.ts
pages/api/admin/directory-sync/[directoryId]/index.ts
pages/api/admin/directory-sync/index.ts
pages/api/admin/license.ts
pages/api/admin/setup-links/index.ts
pages/api/setup/[token]/connections/idp-entityid.ts
pages/api/setup/[token]/connections/index.ts
pages/api/setup/[token]/directory-sync/[directoryId]/index.ts
pages/api/setup/[token]/directory-sync/index.ts
pages/api/setup/[token]/index.ts
pages/api/v1/directory-sync/[directoryId].ts
pages/api/v1/directory-sync/groups/[groupId].ts
pages/api/v1/directory-sync/groups/index.ts
pages/api/v1/directory-sync/index.ts
pages/api/v1/directory-sync/users/[userId].ts
pages/api/v1/directory-sync/users/index.ts

Prevent sending multiple `Allow` headers in the response. The standard approach is to set a comma separated string https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Allow. 
https://github.com/boxyhq/jackson/pull/733#discussion_r1041819699

Prevent sending multiple Allow headers in the response.

---

ee/federated-saml/pages/metadata.tsx
pages/well-known/saml-configuration.tsx

- Display the toast message after the content is copied to the clipboard
- Adjust the width of the content for SP and IdP configuration

fix: display toast and adjust the width of the content

---

npm/src/directory-sync/DirectoryUsers.ts
npm/src/directory-sync/types.ts
npm/src/directory-sync/utils.ts
npm/test/dsync/data/user-requests.ts
npm/test/dsync/users.test.ts

This PR add support to handle multi-valued attributes in SCIM operations in a single PATCH request.
For example
```javascript
Operations: [
{
op: "replace",
path: "name.givenName",
value: "David",
},
{
op: "replace",
path: "name.familyName",
value: "Jones",
},
{
op: "add",
path: "companyName",
value: "BoxyHQ",
},
{
op: "replace",
value: { active: false },
},
];
```
The above request will send an `user.updated` event with updated user payload.

Fix the Directory Sync operations

---

npm/src/controller/connection/saml.ts

It was needed to find connections with the same tenant, product & entityID.
So instead of using getByIndex which was not required using the get method to get the same
Fixes the bug regarding ClientID with JumpCloud use case
JumpCloud Workflow
- Add 2 SSO connections with the same tenant, product & entity id
- Jackson should not create a new `connectionClientSecret`

Jumpcloud fixes

---

npm/src/controller/utils.ts
npm/src/directory-sync/non-scim/google/api.ts
npm/src/directory-sync/scim/DirectoryConfig.ts
npm/test/dsync/directories.test.ts
pages/api/v1/directory-sync/products.ts

This PR adds an API to fetch dsync connections by product.
- Added secondary index `product` to the connections
- Added a new endpoint `/api/v1/directory-sync/products` to fetch connections by product

Add API to fetch dsync connections by product

---

pages/api/health.ts

This PR displays the error that the health check has on the server so we are not blind when we have configuration errors.
In case of a misconfiguration error, e.g wrong DB_ENCRYPTION_KEY, the health check fails silently

chore: add logging to the healthcheck in case it fails

---

internal-ui/src/dsync/DirectoryInfo.tsx
internal-ui/src/hooks/useDirectory.tsx

Display Google button only if the directory type is `google`.

Display Google auth button only if the directory type is `google`

---

.env.example
internal-ui/package-lock.json
lib/env.ts
npm/src/controller/oauth.ts
npm/src/index.ts
npm/src/typings.ts
npm/test/sso/oidc_idp_oauth.test.ts
package-lock.json

Adds a new env variable `OIDC_REQUEST_PROFILE_SCOPE` (npm option: `openid.requestProfileScope`). By setting this to false, the `profile` scope will no longer be automatically included in the Authorization request to the OIDC provider. This will enable apps to request the minimum required authorization permissions from the signed in user. Apps can explicitly send the `profile` scope in the request to Jackson which will then be forwarded to the OIDC provider.

Ability to opt out of sending profile scope

---

npm/src/directory-sync/scim/utils.ts
npm/src/directory-sync/types.ts

I discovered that an error was thrown when I changed the name of a group in Azure and tried to provision the group:
```
⨯ npm/src/directory-sync/scim/utils.ts (50:26) @ parseGroupOperation
⨯ TypeError: Cannot use 'in' operator to search for 'displayName' in PreciselyQA/21/Team/FFS2
at parseGroupOperation (webpack-internal:///(api)/./npm/src/directory-sync/scim/utils.ts:57:43)
at DirectoryGroups.patch (webpack-internal:///(api)/./npm/src/directory-sync/scim/DirectoryGroups.ts:98:90)
at DirectoryGroups.handleRequest (webpack-internal:///(api)/./npm/src/directory-sync/scim/DirectoryGroups.ts:262:39)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async RequestHandler.handle (webpack-internal:///(api)/./npm/src/directory-sync/request.ts:16:20)
at async handler …
```

Handle group patches where value is a string

---

e2e/support/fixtures/index.ts
e2e/support/fixtures/setuplink-page.ts
e2e/ui/Enterprise SSO/setup_link.spec.ts
internal-ui/src/hooks/useFetch.ts
internal-ui/src/setup-link/SetupLinks.tsx

Added e2e tests for enterprise SSO setup link

---

.env.example
lib/env.ts
npm/src/controller/oauth.ts
npm/src/index.ts
npm/src/typings.ts
npm/test/sso/oidc_idp_oauth.test.ts

Jackson will be able to forward standard OIDC params to the IdP on the back of `openid.forwardOIDCParams` option ( `OPENID_REQUEST_FORWARD_PARAMS` env)

Relay OpenId params to OIDC Identity providers

---

e2e/support/data/dsync/index.ts
e2e/ui/Enterprise SSO/setup_link.spec.ts
internal-ui/src/types.ts
lib/constants.ts
npm/src/directory-sync/scim/DirectoryConfig.ts
npm/src/directory-sync/types.ts

Azure AD -> Entra ID

---

pages/api/setup/[token]/directory-sync/[directoryId]/index.ts
pages/api/setup/[token]/sso-connection/[id].ts
pages/api/setup/[token]/sso-connection/index.ts

Fix token validation in Setup Link API paths

---

pages/setup/[token]/sso-connection/new.tsx

Use parsed step number to load the file to prevent bypass via non-strict parseInt

Fix for bypassing allowed steps in Setup Links

---

.env.example
lib/env.ts
npm/src/controller/oauth.ts
npm/src/typings.ts

Introduced new config OPENID_SUBJECT_PREFIX to prefix OIDC subject with tenant and product

Added OPENID_SUBJECT_PREFIX config to prefix subject

---

ee/identity-federation/api/oidc/idp-login/[fedAppId].ts
ee/identity-federation/api/sso.ts
lib/utils.ts
pages/api/oauth/authorize.ts
pages/api/oauth/oidc.ts
pages/api/oauth/saml.ts

Error page is always assumed to be at `/error`, but if external url contains a path then this no longer holds true. This PR fixes that and append `error` to external url.

feat: use external url to resolve the path for error pages
